use_frameworks!

abstract_target 'MetaWear' do
    abstract_target 'MetaWear-iOS' do
        platform :ios, '14.5'
        ## LOCAL
	pod 'MetaWear', :subspecs => ['UI', 'AsyncUtils', 'Mocks', 'DFU'], :path => '../'
 	pod 'CoreBluetoothMock'
        
        target 'MetaWearIntegrationTestHost-iOS' do
            target 'MetaWearIntegrationTests-iOS' do
                inherit! :search_paths
            end
        end
        
        target 'MetaWearUnitTests-iOS' do
        end
    end
    
    abstract_target 'MetaWear-macOS' do
        platform :osx, '11.5'
        ## LOCAL
	pod 'MetaWear', :subspecs => ['UI', 'AsyncUtils', 'Mocks', 'DFU'], :path => '../'
	pod 'CoreBluetoothMock'
        
        target 'MetaWearIntegrationTestHost-macOS' do
            target 'MetaWearIntegrationTests-macOS' do
                inherit! :search_paths
            end
        end
        
        target 'MetaWearUnitTests-macOS' do
        end
    end
    
    abstract_target 'MetaWear-tvOS' do
        platform :tvos, '14.5'
        ## LOCAL
        pod 'MetaWear', :subspecs => ['UI', 'AsyncUtils'], :path => '../'
        pod 'CoreBluetoothMock'

        target 'MetaWearIntegrationTestHost-tvOS' do
            target 'MetaWearIntegrationTests-tvOS' do
                inherit! :search_paths
            end
        end
    
        target 'MetaWearUnitTests-tvOS' do
        end
    end
    
    
    abstract_target 'MetaWear-watchOS' do
        platform :watchos, '7.4'
        ## LOCAL
        pod 'MetaWear', :subspecs => ['UI', 'AsyncUtils'], :path => '../'
        pod 'CoreBluetoothMock'        

        target 'MetaWearIntegrationTestHost-watchOS Extension' do
        end
    end
end
